image: python:3.9

variables:
  WORK_DIR: .
  NODE_ENV: development
  DOCKER_DRIVER: overlay2
  DOCKER_FILE: Dockerfile
  DOCKER_BUILD_CONTEXT: .
  DOCKER_IMAGE: flask-app
cache:
  key: '$CI_COMMIT_REF_SLUG'
stages:
  - deploy
Deploy:
  stage: deploy
  only:
    - full-feature
  tags:
    - team-13-runner
  script:
    - docker stop $(docker ps -aq) || true
    - docker build -t ${DOCKER_IMAGE} .
    - docker run -it -d -p 5000:5000 --restart=unless-stopped ${DOCKER_IMAGE}
    - echo "test docker 13 team"
